name: Deploy to Firebase Hosting on merge
on:
  workflow_dispatch:
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - working-directory: ./sky-siren
        run: npm install && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entrypoint: /sky-siren
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SOEN_487_GALACTUS }}'
          channelId: live
          projectId: soen-487-galactus
